#!/bin/bash

socket='/var/run/mysqld/mysqld.sock'
db_source="$1"
db_dest="$2"

if [[ -z $db_dest ]]; then
  mysqldump -uroot --protocol=socket -S $socket $db_source | gzip --stdout --best
else
  if [[ -f $db_source ]]; then
    echo "Restore DB dump..."
    gzip --decompress --stdout --keep $db_source | mysql -uroot --protocol=socket -S $socket $db_dest
  else
    echo "Copying from DB to DB..."
    mysqldump -uroot --protocol=socket -S $socket $db_source | mysql -uroot --protocol=socket -S $socket $db_dest
  fi
fi
