#!/bin/bash

# defaults
def_param='aPh'
custom_project=
custom_path=
out_sync=

for param; do
  if [[ ${param:0:1} == ':' ]]; then
    custom_project=${param:1}
    custom_project=${custom_project%%/*}

  elif [[ ${param:0:2} == '-o' ]]; then
    out_sync=true

  elif [[ $param == '-' ]]; then
    def_param='ah'

  else
    custom_path="$param"
  fi
done

rsync_prj=${custom_project:-fusetube}
rsync_base=$HOME
rsync_dup="$HOME/projects"
rsync_opt=(
  /screenlog.*
  vendor/assets/bower_components
  log/*.*
  images/reflective-*.png
  icons/content-*.png
  icons/transparent-content-*.png
  icons/colour-content-*.png
  solr/data
  solr/pids
  companies/201*.css.scss
  tmp/**
  *.sqlite3
  :memory*
  /.idea
  coverage/**
  public/system/**
  public/assets/**
  .screenlog.*
  .tag*
)

if [ ! $out_sync ]; then
  source_from="./$custom_path/"
  source_to="/$custom_path"
  from="${rsync_base}/${rsync_prj}/${source_from}"
  to="$rsync_dup/$rsync_prj${source_to}"
  perm='--no-p --no-g --chmod=ugo=rwX'
else
  from="${rsync_dup}/${rsync_prj}"
  to="$rsync_base"
fi

unset out_sync;
exclude_options=$(for i in ${rsync_opt[@]}; do echo -n "--exclude '$i' "; done)
rsync -$def_param $perm --delete $exclude_options $from $to
